config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clothing_uses
  resources :garments
  resources :garment_types
  resources :brands
  resources :broadcasts
  resources :hosts

  root 'broadcasts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/garment_types_controller.rb
class GarmentTypesController < ApplicationController
  before_action :set_garment_type, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /garment_types or /garment_types.json
  def index
    @garment_types = GarmentType.all
  end

  # GET /garment_types/1 or /garment_types/1.json
  def show
  end

  # GET /garment_types/new
  def new
    @garment_type = GarmentType.new
  end

  # GET /garment_types/1/edit
  def edit
  end

  # POST /garment_types or /garment_types.json
  def create
    @garment_type = GarmentType.new(garment_type_params)

    respond_to do |format|
      if @garment_type.save
        format.html { redirect_to @garment_type, notice: "Garment type was successfully created." }
        format.json { render :show, status: :created, location: @garment_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @garment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garment_types/1 or /garment_types/1.json
  def update
    respond_to do |format|
      if @garment_type.update(garment_type_params)
        format.html { redirect_to @garment_type, notice: "Garment type was successfully updated." }
        format.json { render :show, status: :ok, location: @garment_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @garment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garment_types/1 or /garment_types/1.json
  def destroy
    @garment_type.destroy
    respond_to do |format|
      format.html { redirect_to garment_types_url, notice: "Garment type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garment_type
      @garment_type = GarmentType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garment_type_params
      params.require(:garment_type).permit(:name)
    end
end

app/helpers/garment_types_helper.rb
module GarmentTypesHelper
end

app/views/garment_types/_form.html.erb
<%= form_with(model: garment_type) do |form| %>
  <% if garment_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garment_type.errors.count, "error") %> prohibited this garment_type from being saved:</h2>

      <ul>
        <% garment_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/garment_types/edit.html.erb
<h1>Editing Garment Type</h1>

<%= render 'form', garment_type: @garment_type %>

<%= link_to 'Show', @garment_type %> |
<%= link_to 'Back', garment_types_path %>

app/views/garment_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Garment Types</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @garment_types.each do |garment_type| %>
      <tr>
        <td><%= garment_type.name %></td>
        <td><%= link_to 'Show', garment_type %></td>
        <td><%= link_to 'Edit', edit_garment_type_path(garment_type) %></td>
        <td><%= link_to 'Destroy', garment_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garment Type', new_garment_type_path, class: "btn btn-primary", style: "color:white" %>

app/views/garment_types/new.html.erb
<h1>New Garment Type</h1>

<%= render 'form', garment_type: @garment_type %>

<%= link_to 'Back', garment_types_path %>

app/views/garment_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @garment_type.name %>
</p>

<%= link_to 'Edit', edit_garment_type_path(@garment_type) %> |
<%= link_to 'Back', garment_types_path %>