config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clothing_uses
  resources :garments
  resources :garment_types
  resources :brands
  resources :broadcasts
  resources :hosts

  root 'broadcasts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/host.rb
class Host < ApplicationRecord
  def full_name
    first_name + " " + last_name
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /hosts or /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1 or /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts or /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: "Host was successfully created." }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1 or /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: "Host was successfully updated." }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1 or /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: "Host was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def host_params
      params.require(:host).permit(:first_name, :last_name, :sex, :age)
    end
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<%= form_with(model: host) do |form| %>
  <% if host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
        <% host.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :sex, class: "form-label" %>
    <%= form.number_field :sex, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :age, class: "form-label" %>
    <%= form.number_field :age, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hosts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Sex</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.first_name %></td>
        <td><%= host.last_name %></td>
        <td><%= host.sex %></td>
        <td><%= host.age %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host', new_host_path, class: "btn btn-primary", style: "color:white" %>

app/views/hosts/new.html.erb
<h1>New Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @host.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @host.last_name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @host.sex %>
</p>

<p>
  <strong>Age:</strong>
  <%= @host.age %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>