config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clothing_uses
  resources :garments
  resources :garment_types
  resources :brands
  resources :broadcasts
  resources :hosts

  root 'broadcasts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-xl navbar" style="background-color: #3FFF00;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Clothing</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarLight" aria-controls="navbarLight"  aria-expanded="false" aria-label="Toggle navigation"  >
      <span class="navbar-toggler-icon" ></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarLight">
      <ul class="navbar-nav me-auto mb-2 mb-xl-0">
        <li class="nav-item">
          <%= link_to "Garments", garments_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Hosts", hosts_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Broadcast", broadcasts_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Clothing Use", clothing_uses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Garment Types", garment_types_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Brands", brands_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
    <%= render 'layouts/users' %>
  </div>
</nav>

app/views/layouts/_users.html.erb
<div class="collapse navbar-collapse show" id="navbarWithDropdown">
  <ul class="navbar-nav">
    <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle btn" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <span><%= current_user.email %></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><%= link_to "Editar Perfil", edit_user_registration_path, class: "btn" %></li>
          <hr>
          <li><%= link_to "Cerrar Sesión", destroy_user_session_path, class: "btn",  method: :delete  %></li>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vestimenta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render :partial => 'layouts/menu' %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>